version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads 